/* GENERATED FILE: vs_lib_defs_gl.h */
#ifndef FREEGLUT_LIB_DEFS_GL_H
#define FREEGLUT_LIB_DEFS_GL_H

#ifndef VS_GL_SO_NAME
#else

#define glAlphaFunc                          (*vs_glAlphaFunc)
#define glBegin                              (*vs_glBegin)
#define glBindTexture                        (*vs_glBindTexture)
#define glBlendFunc                          (*vs_glBlendFunc)
#define glCallList                           (*vs_glCallList)
#define glClear                              (*vs_glClear)
#define glClearColor                         (*vs_glClearColor)
#define glClearDepth                         (*vs_glClearDepth)
#define glColor3f                            (*vs_glColor3f)
#define glColor4f                            (*vs_glColor4f)
#define glColor4fv                           (*vs_glColor4fv)
#define glColorMask                          (*vs_glColorMask)
#define glColorMaterial                      (*vs_glColorMaterial)
#define glCullFace                           (*vs_glCullFace)
#define glDeleteLists                        (*vs_glDeleteLists)
#define glDeleteTextures                     (*vs_glDeleteTextures)
#define glDepthFunc                          (*vs_glDepthFunc)
#define glDepthMask                          (*vs_glDepthMask)
#define glDisable                            (*vs_glDisable)
#define glDrawArrays                         (*vs_glDrawArrays)
#define glDrawElements                       (*vs_glDrawElements)
#define glEnable                             (*vs_glEnable)
#define glEnableClientState                  (*vs_glEnableClientState)
#define glEnd                                (*vs_glEnd)
#define glEndList                            (*vs_glEndList)
#define glFinish                             (*vs_glFinish)
#define glFlush                              (*vs_glFlush)
#define glFogf                               (*vs_glFogf)
#define glFogfv                              (*vs_glFogfv)
#define glFogi                               (*vs_glFogi)
#define glGenLists                           (*vs_glGenLists)
#define glGenTextures                        (*vs_glGenTextures)
#define glGetError                           (*vs_glGetError)
#define glGetFloatv                          (*vs_glGetFloatv)
#define glGetIntegerv                        (*vs_glGetIntegerv)
#define glGetString                          (*vs_glGetString)
#define glInterleavedArrays                  (*vs_glInterleavedArrays)
#define glIsEnabled                          (*vs_glIsEnabled)
#define glIsList                             (*vs_glIsList)
#define glLightf                             (*vs_glLightf)
#define glLightfv                            (*vs_glLightfv)
#define glLightModelfv                       (*vs_glLightModelfv)
#define glLightModeli                        (*vs_glLightModeli)
#define glLineWidth                          (*vs_glLineWidth)
#define glLoadIdentity                       (*vs_glLoadIdentity)
#define glLoadMatrixd                        (*vs_glLoadMatrixd)
#define glLoadMatrixf                        (*vs_glLoadMatrixf)
#define glMaterialfv                         (*vs_glMaterialfv)
#define glMatrixMode                         (*vs_glMatrixMode)
#define glNewList                            (*vs_glNewList)
#define glNormal3f                           (*vs_glNormal3f)
#define glNormal3fv                          (*vs_glNormal3fv)
#define glPixelStorei                        (*vs_glPixelStorei)
#define glPointSize                          (*vs_glPointSize)
#define glPolygonMode                        (*vs_glPolygonMode)
#define glPolygonOffset                      (*vs_glPolygonOffset)
#define glPopMatrix                          (*vs_glPopMatrix)
#define glPrioritizeTextures                 (*vs_glPrioritizeTextures)
#define glPushMatrix                         (*vs_glPushMatrix)
#define glRasterPos2f                        (*vs_glRasterPos2f)
#define glReadPixels                         (*vs_glReadPixels)
#define glRectf                              (*vs_glRectf)
#define glScaled                             (*vs_glScaled)
#define glScalef                             (*vs_glScalef)
#define glScissor                            (*vs_glScissor)
#define glShadeModel                         (*vs_glShadeModel)
#define glStencilFunc                        (*vs_glStencilFunc)
#define glStencilMask                        (*vs_glStencilMask)
#define glStencilOp                          (*vs_glStencilOp)
#define glTexCoord2f                         (*vs_glTexCoord2f)
#define glTexCoordPointer                    (*vs_glTexCoordPointer)
#define glTexEnvfv                           (*vs_glTexEnvfv)
#define glTexEnvi                            (*vs_glTexEnvi)
#define glTexGenfv                           (*vs_glTexGenfv)
#define glTexGeni                            (*vs_glTexGeni)
#define glTexImage2D                         (*vs_glTexImage2D)
#define glTexParameterf                      (*vs_glTexParameterf)
#define glTexParameterfv                     (*vs_glTexParameterfv)
#define glTexParameteri                      (*vs_glTexParameteri)
#define glTexSubImage2D                      (*vs_glTexSubImage2D)
#define glTranslated                         (*vs_glTranslated)
#define glTranslatef                         (*vs_glTranslatef)
#define gluBuild2DMipmaps                    (*vs_gluBuild2DMipmaps)
#define gluErrorString                       (*vs_gluErrorString)
#define glVertex2f                           (*vs_glVertex2f)
#define glVertex3d                           (*vs_glVertex3d)
#define glVertex3f                           (*vs_glVertex3f)
#define glVertex3fv                          (*vs_glVertex3fv)
#define glViewport                           (*vs_glViewport)
#define glXGetProcAddressARB                 (*vs_glXGetProcAddressARB)

#endif /* ! ifndef VS_GL_SO_NAME */
#endif /* ! ifndef FREEGLUT_LIB_DEFS_GL_H */

